export enum RootScreens {
  MAIN = 'Main',
  WELCOME = 'Welcome',
  ONBOARDING = 'Onboarding',
  NOT_FOUND = '*',
  SIGNIN = 'SignIn',
  SIGNUP = 'SignUp',
  HOME = 'Home',
  ROOMING_HOUSED_DETAIL = 'RoomingHouseDetail',
  ROOMING_HOUSE_LIST = 'RoomingHouseList',
  INVOICE = 'Invoice',
  FINANCE = 'Finance',
  PROFILE = 'Profile',
  CREATE_ROOMING_HOUSE = 'CreateRoomingHouse',
  FLOORDETAIL = 'FloorDetail',
  ROOMDETAIL = 'RoomDetail',
  CREATE_FLOOR = 'CreateFloor',
  CREATE_ROOM = 'CreateRoom',
  CREATE_CONTRACT = 'CreateContract',
  CONTRACT_DETAIL = 'ContractDetail',
  CREATE_DEVICE = 'CreateDevice',
  DEVICE_DETAIL = 'DeviceDetail',
  NOTIFICATION = 'Notification',
  ADD_TENANT = 'AddTenant',
}
